{{- if .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "promitor-agent-resource-discovery.secretname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promitor-agent-resource-discovery.labels" . | nindent 4 }}
type: Opaque
data:
{{- if contains "managedIdentity" .Values.azureAuthentication.mode }}
  {{- if empty .Values.azureAuthentication.managedIdentityId | not }} 
  {{ .Values.secrets.managedIdentityIdSecret }}: {{ .Values.azureAuthentication.managedIdentityId | b64enc | quote }}
  {{- end }}
{{- else }}
  {{ .Values.secrets.appIdSecret }}: {{ .Values.azureAuthentication.appId | b64enc | quote }}
  {{ .Values.secrets.appKeySecret }}: {{ .Values.azureAuthentication.appKey | b64enc | quote }}
{{- end }}
{{- end }}
